[package]
name = "untitled1"
version = "0.1.0"
edition = "2024"
include = ["assets/*"]

[dependencies]
piston = "0.53.0"
piston2d-graphics = "0.39.0"
piston_window = "0.120.0"
pistoncore-glutin_window = "0.70.0"
rand = "0.8.5"